language: python
python: 2.7
cache:
  pip: true
  directories:
    - $HOME/downloads
env:
  - SOLR_VERSION=4.5.1
#matrix:
#  allow_failures:
#    - env: SOLR_VERSION=5.0.0
before_install:
  - mkdir -p $HOME/downloads
  - sed -ie "s#SOLR_VERSION := 4.5.1#SOLR_VERSION := $SOLR_VERSION#" Makefile
install:
  - make
script:
  - py.test
