language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - $HOME/downloads
    - /home/travis/build/tisto/solr-testing/downloads
env:
  - SOLR_VERSION=4.5.1
  - SOLR_VERSION=4.9.1
  - SOLR_VERSION=5.5.3
matrix:
  allow_failures:
    - env: SOLR_VERSION=5.5.3
before_install:
  - mkdir -p $HOME/downloads
  - sed -ie "s#SOLR_VERSION := 4.5.1#SOLR_VERSION := $SOLR_VERSION#" Makefile
install:
  - pip install -r requirements.txt
  - make
script:
  - py.test -v
